# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diffusion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='heat_transfer_coefficient',
            field=models.FloatField(default=0),
        ),
    ]
