# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diffusion', '0002_auto_20160511_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnealRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=50)),
                ('treatment_name', models.CharField(max_length=100)),
                ('data', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='contactprofile',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
